<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>KikuKegel.Windows</AssemblyName>
    <RootNamespace>KikuKegel.Windows</RootNamespace>
    <Version>0.2.0</Version>
    <FileVersion>0.2.0.0</FileVersion>
    <AssemblyVersion>0.2.0.0</AssemblyVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
</Project>
